version: '3'
services:
  nginx:
    image: nginx:stable-alpine
    ports:
      - 8888:80
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    restart: always

  portalweb:
    image: mophos/r7platform-portal-web
    restart: always
    depends_on:
      - nginx
      
  portalapi:
    image: mophos/r7platform-portal-api
    environment:
      - NODE_ENV=production
      - R7PLATFORM_PORTAL_API_DB_HOST=host.docker.internal
      - R7PLATFORM_PORTAL_API_DB_PORT=5432
      - R7PLATFORM_PORTAL_API_DB_NAME=r7platform
      - R7PLATFORM_PORTAL_API_DB_SCHEMA=libs
      - R7PLATFORM_PORTAL_API_DB_USER=postgres
      - R7PLATFORM_PORTAL_API_DB_PASSWORD=xxxxx
      - R7PLATFORM_PORTAL_API_DB_RAW_HOST=host.docker.internal
      - R7PLATFORM_PORTAL_API_DB_RAW_PORT=5432
      - R7PLATFORM_PORTAL_API_DB_RAW_NAME=r7platform
      - R7PLATFORM_PORTAL_API_DB_RAW_SCHEMA=rawdata
      - R7PLATFORM_PORTAL_API_DB_RAW_USER=postgres
      - R7PLATFORM_PORTAL_API_DB_RAW_PASSWORD=xxxxxx
      - R7PLATFORM_PORTAL_API_SECRET_KEY=xxxxx32bitxxxxx
      - R7PLATFORM_PORTAL_API_LOGIN_ENDPOINT=https://r7.moph.go.th/platform/auth
    restart: always
    extra_hosts: 
      - "host.docker.internal:host-gateway"
    depends_on:
      - nginx
     
