version: '3'
services:
  nginx:
    image: nginx:stable-alpine
    ports:
      - 8881:80
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    restart: always
    links:
      - usmweb
      - usmapi

  usmweb:
    image: mophos/r7platform-usm-web
    restart: always
      
  usmapi:
    image: mophos/r7platform-usm-api
    environment:
      - NODE_ENV=production
      - R7PLATFORM_USM_DB_HOST=host.docker.internal
      - R7PLATFORM_USM_DB_PORT=5432
      - R7PLATFORM_USM_DB_NAME=r7platform
      - R7PLATFORM_USM_DB_SCHEMA=users
      - R7PLATFORM_USM_DB_USER=postgres
      - R7PLATFORM_USM_DB_PASSWORD=xxxxx
      - R7PLATFORM_USM_DB_POOL_MAX=10
      - R7PLATFORM_USM_DB_POOL_MIN=0
      - R7PLATFORM_USM_SECRET_KEY=xxxxx32bitxxxxx
      - R7PLATFORM_USM_SERVICE_HOSTNAME=Doraemon
    restart: always
    extra_hosts: 
      - "host.docker.internal:host-gateway"
